// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCl82NG0XCO4lHtnCp7THhlMdp18hr-R6M',
    appId: '1:604826370193:web:9f67bd1d949889a88fff30',
    messagingSenderId: '604826370193',
    projectId: 'crud-36dd2',
    authDomain: 'crud-36dd2.firebaseapp.com',
    storageBucket: 'crud-36dd2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZ9pj54VTUIjO3SM0k39Mkg7S43SyNp8s',
    appId: '1:604826370193:android:f726a11343c1867a8fff30',
    messagingSenderId: '604826370193',
    projectId: 'crud-36dd2',
    storageBucket: 'crud-36dd2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCy8bYeSp87coOWeWHx-NJfaOjYWnhn9bU',
    appId: '1:604826370193:ios:962de7747792e9668fff30',
    messagingSenderId: '604826370193',
    projectId: 'crud-36dd2',
    storageBucket: 'crud-36dd2.appspot.com',
    iosBundleId: 'com.example.crud',
  );
}
